#!/bin/bash

mkdir build && cd build

cmake ${CMAKE_ARGS} -LAH -G "Ninja" \
  -DCMAKE_PREFIX_PATH="$PREFIX" \
  -DCMAKE_FIND_FRAMEWORK=NEVER \
  -DCMAKE_INSTALL_PREFIX="$PREFIX" \
  -DCMAKE_INSTALL_RPATH="${PREFIX}/lib" -DCMAKE_BUILD_WITH_INSTALL_RPATH=ON \
  -DCMAKE_INSTALL_LIBDIR=lib \
  -DCMAKE_BUILD_TYPE="Release"  \
  -DBUILD_SHARED_LIBS=ON \
  -DDLIB_NO_GUI_SUPPORT=ON \
  -DDLIB_GIF_SUPPORT=OFF \
  -DDLIB_LINK_WITH_SQLITE3=OFF \
  -DDLIB_WEBP_SUPPORT=OFF \
  -DDLIB_USE_FFMPEG=OFF \
  -DDLIB_USE_CUDA=OFF \
  ..
cmake --build . --target install
