{% set version = "19.17" %}

package:
  name: dlib-cpp
  version: {{ version }}

source:
  url: https://github.com/davisking/dlib/archive/v{{ version }}.tar.gz
  sha256: 9d2a158b2adad6acba2346f90d929558a691151aa076a0b409ee685534118692
  patches:
    # https://github.com/conda-forge/conda-forge.github.io/issues/785
    - cxx11_detection.patch

build:
  skip: true  # [win and vc<14]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
  host:
    - liblapack   # [not win]
    - libcblas  # [not win]
    - jpeg
    - libpng
  run:
    - jpeg
    - libpng

test:
  commands:
    - test -f ${PREFIX}/include/dlib/svm.h  # [unix]
    - test -f ${PREFIX}/lib/libdlib${SHLIB_EXT}  # [unix]
    - if not exist %PREFIX%\\Library\\include\\dlib\\svm.h exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\dlib{{ version }}.0_release_64bit_msvc1900.lib exit 1  # [win]

about:
  home: http://dlib.net/
  license: BSL-1.0
  license_file: dlib/LICENSE.txt
  summary: Modern C++ toolkit containing machine learning algorithms

extra:
  recipe-maintainers:
    - jschueller
