{% set version = "19.24.2" %}

package:
  name: dlib-cpp
  version: {{ version }}

source:
  url: https://github.com/davisking/dlib/archive/v{{ version }}.tar.gz
  sha256: 0f5c7e3de6316a513635052c5f0a16a84e1cef26a7d233bf00c21348462b6d6f
  patches:
    # https://github.com/davisking/dlib/pull/2817
    - cblas.patch

build:
  number: 3
  run_exports:
    - {{ pin_subpackage('dlib-cpp', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - pkg-config  # [unix]
  host:
    - liblapack   # [not win]
    - libcblas  # [not win]
    - libjpeg-turbo
    - libpng
    - zlib

test:
  commands:
    - test -f ${PREFIX}/include/dlib/svm.h  # [unix]
    - test -f ${PREFIX}/lib/libdlib${SHLIB_EXT}  # [unix]
    - if not exist %PREFIX%\\Library\\include\\dlib\\svm.h exit 1  # [win]

about:
  home: http://dlib.net/
  license: BSL-1.0
  license_file: dlib/LICENSE.txt
  summary: Modern C++ toolkit containing machine learning algorithms

extra:
  recipe-maintainers:
    - jschueller
