{% set version = "19.24.6" %}

package:
  name: dlib-cpp
  version: {{ version }}

source:
  url: https://github.com/davisking/dlib/archive/v{{ version }}.tar.gz
  sha256: 22513c353ec9c153300c394050c96ca9d088e02966ac0f639e989e50318c82d6

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('dlib-cpp', max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - pkg-config  # [unix]
  host:
    - liblapack   # [not win]
    - libcblas  # [not win]
    - libjpeg-turbo
    - libpng
    - zlib

test:
  commands:
    - test -f ${PREFIX}/include/dlib/svm.h  # [unix]
    - test -f ${PREFIX}/lib/libdlib${SHLIB_EXT}  # [unix]
    - if not exist %PREFIX%\\Library\\include\\dlib\\svm.h exit 1  # [win]

about:
  home: http://dlib.net/
  license: BSL-1.0
  license_file: dlib/LICENSE.txt
  summary: Modern C++ toolkit containing machine learning algorithms

extra:
  recipe-maintainers:
    - jschueller
