travis:
  secure:
    BINSTAR_TOKEN: XFvnwPcIMmDyNwUDa0pg3nNH+R1ijaIJyWyEmHdMnDRsV8ChsWATqXlWcmDN0es33WwEnWgZ1QY1hyW4a+zP7qWmABI9kiCBCRkKYOJ7CGNxXhkQ6y2waVIUlsphkdDFjtCJPxeD8SktoOFGn49Slt+LoYzXWOSGdtMYUVvK9j4S2qhDVW4+tElhFaX7KZb/GyIYDgnfCbLb/BY7UBDACOrkgWY+5o5IAkH/MZ06r237ICD2HSy86DQOzto/mdzQA0zsDNTdLZca00j03MadHCl3v4CLPfJ0EbiaVCb3TrKWnmWCcV3hl8dD63HDAt5TKgmIB42141Zmw076+A+7HtcLOSN+wqiWRug3G3hVtdI8huBgmKc/fLx6KWVuOOc0JOG41xF3tv91vzztYerVmagTuYQkpMrWUXpnsZP/uvSJ74o5jsgVRtwXCjd+a0coJzu6QBzCNl6Wpm86lop/fk7v897Ws+zFtAJId4ocWjekzX+XLyAF0VQ0OS2dqjxphCnDxpynxZsAV0WbL1TaxSrCfaPpBZmV7O6BQdtsBy1okv/kKsQrJTa8MOY+gy66F6Dz7hR4u23d6RBt6iihFbznycTFPFNTpaZU5yzyZzQ55eBRewpKpY6/mVxVNVz12g9+iiF25TUCpru/FTEsbXq7tqbUsWmmXJc3QyC0sGc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
